# Site Settings
title: Adam Sniderman
email: adam.sniderman@mail.utoronto.ca
description: >      # Ignore new lines in this section
	Engineering mathematician. Robotics/tech enthusiast. Ph.D. candidate. Read on?
baseurl: ""
# url: "www.adamsniderman.com"
twitter_username: AdamSniderman
github_username:  asnid

# Build Settings
markdown:kramdown
